server {                                   # описание одного виртуального хоста
    listen       80;                       # слушаем 80 порт внутри контейнера
    server_name  _;                        # "_" = отвечаем на любой домен/хост
 
    root   /usr/share/nginx/html;          # откуда отдавать файлы
    index  index.html;
 
    location / {
        try_files $uri $uri/ /index.html;  # ищем файл → папку → fallback
    }
}
